CREATE TABLE `reservations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`unitCota` varchar(32) NOT NULL,
	`unitTipologia` varchar(32),
	`unitAndar` varchar(32),
	`unitValorTotal` varchar(32),
	`nomeCompleto` varchar(256) NOT NULL,
	`dataNascimento` varchar(16),
	`nacionalidade` varchar(64),
	`naturalidade` varchar(64),
	`endereco` varchar(256),
	`complemento` varchar(128),
	`bairro` varchar(128),
	`cep` varchar(16),
	`cidade` varchar(128),
	`telefoneCelular` varchar(32),
	`telefoneResidencial` varchar(32),
	`email` varchar(320) NOT NULL,
	`cpfRnm` varchar(32),
	`orgaoExpeditor` varchar(64),
	`dataExpedicao` varchar(16),
	`profissao` varchar(128),
	`estadoCivil` varchar(64),
	`regimeComunhao` varchar(64),
	`imobiliaria` varchar(128),
	`responsavelVenda` varchar(128),
	`status` enum('pendente','enviada','confirmada') NOT NULL DEFAULT 'pendente',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reservations_id` PRIMARY KEY(`id`)
);
